# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='PackageMessage.proto',
  package='',
  serialized_pb='\n\x14PackageMessage.proto\"\xa4\x02\n\x0ePackageMessage\x12\r\n\x05Token\x18\x01 \x01(\t\x12\x11\n\tSessionId\x18\x02 \x02(\t\x12\x0c\n\x04Time\x18\x03 \x01(\x03\x12\x0c\n\x04\x46rom\x18\x04 \x01(\t\x12\n\n\x02To\x18\x05 \x01(\t\x12)\n\x0b\x43\x61llMessage\x18\x06 \x01(\x0b\x32\x14.PackageMessage.Call\x12-\n\rResultMessage\x18\x07 \x01(\x0b\x32\x16.PackageMessage.Result\x1a=\n\x04\x43\x61ll\x12\x0f\n\x07Service\x18\x01 \x01(\t\x12\x10\n\x08\x46unction\x18\x02 \x02(\t\x12\x12\n\nParameters\x18\x03 \x03(\x0c\x1a/\n\x06Result\x12\x11\n\tErrorCode\x18\x01 \x02(\x05\x12\x12\n\nResultData\x18\x02 \x01(\x0c')




_PACKAGEMESSAGE_CALL = descriptor.Descriptor(
  name='Call',
  full_name='PackageMessage.Call',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Service', full_name='PackageMessage.Call.Service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Function', full_name='PackageMessage.Call.Function', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Parameters', full_name='PackageMessage.Call.Parameters', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=207,
  serialized_end=268,
)

_PACKAGEMESSAGE_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='PackageMessage.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ErrorCode', full_name='PackageMessage.Result.ErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ResultData', full_name='PackageMessage.Result.ResultData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=270,
  serialized_end=317,
)

_PACKAGEMESSAGE = descriptor.Descriptor(
  name='PackageMessage',
  full_name='PackageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Token', full_name='PackageMessage.Token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SessionId', full_name='PackageMessage.SessionId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Time', full_name='PackageMessage.Time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='From', full_name='PackageMessage.From', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='To', full_name='PackageMessage.To', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='CallMessage', full_name='PackageMessage.CallMessage', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ResultMessage', full_name='PackageMessage.ResultMessage', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PACKAGEMESSAGE_CALL, _PACKAGEMESSAGE_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=317,
)

_PACKAGEMESSAGE_CALL.containing_type = _PACKAGEMESSAGE;
_PACKAGEMESSAGE_RESULT.containing_type = _PACKAGEMESSAGE;
_PACKAGEMESSAGE.fields_by_name['CallMessage'].message_type = _PACKAGEMESSAGE_CALL
_PACKAGEMESSAGE.fields_by_name['ResultMessage'].message_type = _PACKAGEMESSAGE_RESULT
DESCRIPTOR.message_types_by_name['PackageMessage'] = _PACKAGEMESSAGE

class PackageMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Call(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PACKAGEMESSAGE_CALL
    
    # @@protoc_insertion_point(class_scope:PackageMessage.Call)
  
  class Result(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PACKAGEMESSAGE_RESULT
    
    # @@protoc_insertion_point(class_scope:PackageMessage.Result)
  DESCRIPTOR = _PACKAGEMESSAGE
  
  # @@protoc_insertion_point(class_scope:PackageMessage)

# @@protoc_insertion_point(module_scope)
