Header header
int32 LF_Encoder
int32 RF_Encoder
int32 LB_Encoder
int32 RB_Encoder
int8 LFMotor_Status
int8 RFMotor_Status
int8 LBMotor_Status
int8 RBMotor_Status
string LFMotor_Error
string RFMotor_Error
string LBMotor_Error
string RBMotor_Error
int8 TEMP_Chassis
int8 Battery_Power
int16 Battery_Volt
int16 Battery_Current
int8 Battery_Temp
uint16 Obt1_Dis
uint16 Obt2_Dis
uint16 Obt3_Dis
int8 FC_Alarm
int8 OA_Alarm
int8 ES_Alarm
int8 FP_Alarm
int8 BC_Status
int8 LFW_Status
int8 RFW_Status
int8 LBW_Status
int8 RBW_Status
int8 OBT_Status
int8 BMS_Status
int8 FP1_Status
int8 FP2_Status
uint16 FP1_Dis
uint16 FP2_Dis
int16 LF_Torque
int16 RF_Torque
int16 LB_Torque
int16 RB_Torque




