#!/usr/bin/env python

# Copyright (c) 2011, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Willow Garage, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import rospy

from geometry_msgs.msg import Twist
from std_msgs.msg import String
import sys, select, termios, tty

import threading
from pyasn1.compat.octets import null

msg = """
Control Your Turtlebot3!
---------------------------
Moving around:
        w
   a    s    d
        x

w/x : increase/decrease linear velocity
a/d : increase/decrease angular velocity
space key, s : force stop

CTRL-C to quit
"""

soft_key = ''

def SubSoftKeyCallBack():
    rospy.Subscriber("/soft_key", String, SoftKeyCallBack)
    rospy.Subscriber("/cmd_vel", Twist, VelgetCallBack)
    #rospy.Subscriber("/target_speed", Twist, targetVelgetCallBack)

def targetVelgetCallBack(data):
    pass#global commond_linear_vel
    #global commond_angular_vel
    #if data != None:
        #commond_linear_vel = data.linear.x
        #commond_angular_vel = data.angular.z
    #print "commond_linear_vel",commond_linear_vel
    #print "commond_angular_vel",commond_angular_vel
    
def VelgetCallBack(data):
    global control_linear_vel
    global control_angular_vel
    if data != None:
        control_linear_vel = data.linear.x
        control_angular_vel = data.angular.z
    print "control_linear_vel",control_linear_vel
    print "control_angular_vel",control_angular_vel
    
def SoftKeyCallBack(data):
    global soft_key
    soft_key = data.data[0]
    print "soft_key",soft_key
    
def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    global soft_key
    #print "soft_key0000000",soft_key
    if soft_key != '':
        key = soft_key
        soft_key = ''
        print "key=",key,"soft_key=",soft_key
    
    return key

def vels(target_linear_vel, target_angular_vel):
    return "currently:\tlinear vel %s\t angular vel %s " % (target_linear_vel,target_angular_vel)

if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin)

    rospy.init_node('turtlebot3_teleop')
    pub = rospy.Publisher('/cmd_vel', Twist, queue_size=5)
    rate = 20
    r = rospy.Rate(rate)
    
    KeyThread = threading.Thread(target=SubSoftKeyCallBack, args=())
    KeyThread.setDaemon(True)
    KeyThread.start()
    
    status = 0
    global commond_linear_vel
    global commond_angular_vel
    commond_linear_vel = 0.2
    commond_angular_vel = 0.2
    target_linear_vel = 0
    target_angular_vel = 0
    global control_linear_vel
    control_linear_vel = 0
    global control_angular_vel
    control_angular_vel = 0
    try:
        print msg
        while(1):
            key = getKey()
            #print "key 111",key
            if key == 'w' :
                target_linear_vel = commond_linear_vel
                #print "case w"
                target_angular_vel = 0.0
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'x' :
                #target_linear_vel = target_linear_vel - 0.01
                target_linear_vel = -commond_linear_vel
                target_angular_vel = 0.0
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'a' :
                #target_angular_vel = target_angular_vel + 0.1
                target_linear_vel = 0.0
                target_angular_vel = commond_angular_vel
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'd' :
                #target_angular_vel = target_angular_vel - 0.1
                target_linear_vel = 0.0
                target_angular_vel = -commond_angular_vel
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == ' ' or key == 's':
                target_linear_vel   = 0
                #control_linear_vel  = 0
                target_angular_vel  = 0
                #control_angular_vel = 0
                print vels(0, 0)
            elif status == 14 :
                print msg
                status = 0
            else:
                if (key == '\x03'):
                    break

            if target_linear_vel > control_linear_vel:
                control_linear_vel = min( target_linear_vel, control_linear_vel + (0.02/1.0) )
            else:
                control_linear_vel = max( target_linear_vel, control_linear_vel - (0.02/1.0) )

            if target_angular_vel > control_angular_vel:
                control_angular_vel = min( target_angular_vel, control_angular_vel + (0.1/4.0) )
            else:
                control_angular_vel = max( target_angular_vel, control_angular_vel - (0.1/4.0) ) #target_angular_vel

            twist = Twist()
            twist.linear.x = control_linear_vel; twist.linear.y = 0; twist.linear.z = 0
            twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = control_angular_vel
            pub.publish(twist)
            r.sleep()
    except:
        print e

    finally:
        twist = Twist()
        twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        pub.publish(twist)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
