# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='CarConfig.proto',
  package='',
  serialized_pb='\n\x0f\x43\x61rConfig.proto\"\xb2\x03\n\tCarConfig\x12\x0e\n\x06\x44speed\x18\x01 \x01(\x05\x12\x0e\n\x06\x44\x61ngel\x18\x02 \x01(\x05\x12\x14\n\x0cSetBaseSpeed\x18\x03 \x01(\x05\x12\x10\n\x08SetEleTh\x18\x04 \x01(\x05\x12\x12\n\nSetElePidP\x18\x05 \x01(\x02\x12\x12\n\nSetElePidI\x18\x06 \x01(\x02\x12\x12\n\nSetElePidD\x18\x07 \x01(\x02\x12\x19\n\x11SetLaserThreshold\x18\x08 \x01(\x02\x12\x14\n\x0c\x41larmVoltage\x18\t \x01(\x02\x12\x10\n\x08\x41larmSOC\x18\n \x01(\x05\x12\x1b\n\x13\x43trlEnableFobstacle\x18\x0b \x01(\x08\x12\x1b\n\x13\x43trlEnableBobstacle\x18\x0c \x01(\x08\x12\x16\n\x0eSetClearBuffer\x18\r \x01(\x08\x12\x10\n\x08MaxSpeed\x18\x0e \x01(\x02\x12\x10\n\x08MinSpeed\x18\x0f \x01(\x02\x12\x12\n\nAngleSpeed\x18\x10 \x01(\x02\x12\x14\n\x0c\x44istanceSlow\x18\x11 \x01(\x02\x12\x1d\n\x15SetLaserThresholdStop\x18\x12 \x01(\x02\x12\x1f\n\x17SetLaserThresholdSector\x18\x13 \x01(\x02')




_CARCONFIG = descriptor.Descriptor(
  name='CarConfig',
  full_name='CarConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Dspeed', full_name='CarConfig.Dspeed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Dangel', full_name='CarConfig.Dangel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetBaseSpeed', full_name='CarConfig.SetBaseSpeed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetEleTh', full_name='CarConfig.SetEleTh', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetElePidP', full_name='CarConfig.SetElePidP', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetElePidI', full_name='CarConfig.SetElePidI', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetElePidD', full_name='CarConfig.SetElePidD', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetLaserThreshold', full_name='CarConfig.SetLaserThreshold', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='AlarmVoltage', full_name='CarConfig.AlarmVoltage', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='AlarmSOC', full_name='CarConfig.AlarmSOC', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='CtrlEnableFobstacle', full_name='CarConfig.CtrlEnableFobstacle', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='CtrlEnableBobstacle', full_name='CarConfig.CtrlEnableBobstacle', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetClearBuffer', full_name='CarConfig.SetClearBuffer', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='MaxSpeed', full_name='CarConfig.MaxSpeed', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='MinSpeed', full_name='CarConfig.MinSpeed', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='AngleSpeed', full_name='CarConfig.AngleSpeed', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='DistanceSlow', full_name='CarConfig.DistanceSlow', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetLaserThresholdStop', full_name='CarConfig.SetLaserThresholdStop', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SetLaserThresholdSector', full_name='CarConfig.SetLaserThresholdSector', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=454,
)

DESCRIPTOR.message_types_by_name['CarConfig'] = _CARCONFIG

class CarConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CARCONFIG
  
  # @@protoc_insertion_point(class_scope:CarConfig)

# @@protoc_insertion_point(module_scope)
