# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='WeatherMessage.proto',
  package='',
  serialized_pb='\n\x14WeatherMessage.proto\"\xaf\x02\n\x0eWeatherMessage\x12\'\n\nGpsMessage\x18\x01 \x01(\x0b\x32\x13.WeatherMessage.Gps\x12\x0c\n\x04Temp\x18\x02 \x01(\x02\x12\x0c\n\x04Humi\x18\x03 \x01(\x02\x12\r\n\x05Speed\x18\x04 \x01(\x02\x12\x0c\n\x04Rain\x18\x05 \x01(\x02\x12\x0c\n\x04Snow\x18\x06 \x01(\x02\x12)\n\x0bModeMessage\x18\x07 \x01(\x0b\x32\x14.WeatherMessage.Mode\x1aG\n\x03Gps\x12\x0c\n\x04Time\x18\x01 \x02(\t\x12\x0b\n\x03Lat\x18\x02 \x01(\t\x12\x0b\n\x03Lon\x18\x03 \x01(\t\x12\x0c\n\x04Nosv\x18\x04 \x01(\x03\x12\n\n\x02\x46s\x18\x05 \x01(\x03\x1a\x39\n\x04Mode\x12\x10\n\x08WorkMode\x18\x01 \x01(\x03\x12\x0c\n\x04Rate\x18\x02 \x01(\x03\x12\x11\n\tErrorCode\x18\x03 \x01(\x03')




_WEATHERMESSAGE_GPS = descriptor.Descriptor(
  name='Gps',
  full_name='WeatherMessage.Gps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='Time', full_name='WeatherMessage.Gps.Time', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Lat', full_name='WeatherMessage.Gps.Lat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Lon', full_name='WeatherMessage.Gps.Lon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Nosv', full_name='WeatherMessage.Gps.Nosv', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Fs', full_name='WeatherMessage.Gps.Fs', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=198,
  serialized_end=269,
)

_WEATHERMESSAGE_MODE = descriptor.Descriptor(
  name='Mode',
  full_name='WeatherMessage.Mode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='WorkMode', full_name='WeatherMessage.Mode.WorkMode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Rate', full_name='WeatherMessage.Mode.Rate', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ErrorCode', full_name='WeatherMessage.Mode.ErrorCode', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=271,
  serialized_end=328,
)

_WEATHERMESSAGE = descriptor.Descriptor(
  name='WeatherMessage',
  full_name='WeatherMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='GpsMessage', full_name='WeatherMessage.GpsMessage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Temp', full_name='WeatherMessage.Temp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Humi', full_name='WeatherMessage.Humi', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Speed', full_name='WeatherMessage.Speed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Rain', full_name='WeatherMessage.Rain', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='Snow', full_name='WeatherMessage.Snow', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ModeMessage', full_name='WeatherMessage.ModeMessage', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WEATHERMESSAGE_GPS, _WEATHERMESSAGE_MODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=328,
)

_WEATHERMESSAGE_GPS.containing_type = _WEATHERMESSAGE;
_WEATHERMESSAGE_MODE.containing_type = _WEATHERMESSAGE;
_WEATHERMESSAGE.fields_by_name['GpsMessage'].message_type = _WEATHERMESSAGE_GPS
_WEATHERMESSAGE.fields_by_name['ModeMessage'].message_type = _WEATHERMESSAGE_MODE
DESCRIPTOR.message_types_by_name['WeatherMessage'] = _WEATHERMESSAGE

class WeatherMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Gps(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _WEATHERMESSAGE_GPS
    
    # @@protoc_insertion_point(class_scope:WeatherMessage.Gps)
  
  class Mode(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _WEATHERMESSAGE_MODE
    
    # @@protoc_insertion_point(class_scope:WeatherMessage.Mode)
  DESCRIPTOR = _WEATHERMESSAGE
  
  # @@protoc_insertion_point(class_scope:WeatherMessage)

# @@protoc_insertion_point(module_scope)
