# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RosStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RosStatus.proto',
  package='',
  serialized_pb=_b('\n\x0fRosStatus.proto\"\x85\x01\n\tRosStatus\x12\x16\n\x0e\x61rbotix_status\x18\x01 \x01(\x05\x12\x13\n\x0b\x61mcl_status\x18\x02 \x01(\x05\x12\x14\n\x0claser_status\x18\x03 \x01(\x05\x12\x10\n\x08ros_info\x18\x04 \x01(\t\x12\x10\n\x08ros_warn\x18\x05 \x01(\t\x12\x11\n\tros_error\x18\x06 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROSSTATUS = _descriptor.Descriptor(
  name='RosStatus',
  full_name='RosStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arbotix_status', full_name='RosStatus.arbotix_status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amcl_status', full_name='RosStatus.amcl_status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laser_status', full_name='RosStatus.laser_status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ros_info', full_name='RosStatus.ros_info', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ros_warn', full_name='RosStatus.ros_warn', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ros_error', full_name='RosStatus.ros_error', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['RosStatus'] = _ROSSTATUS

RosStatus = _reflection.GeneratedProtocolMessageType('RosStatus', (_message.Message,), dict(
  DESCRIPTOR = _ROSSTATUS,
  __module__ = 'RosStatus_pb2'
  # @@protoc_insertion_point(class_scope:RosStatus)
  ))
_sym_db.RegisterMessage(RosStatus)


# @@protoc_insertion_point(module_scope)
